all:
  children:
    Edge: # edge-routers
      children:  # under-group must have children
        huaweiEDGE: # group huawei
          hosts: # list hosts
            EDGE-SARATOV: # name
              ansible_host: 172.16.100.1
              ansible_user: huawei
    Core: # core-routers
      children:
        ecorouter:
          hosts:
            CORE-SARATOV:
              ansible_host: 172.16.100.2
              ansible_user: admin
    PE: # PE-routers
      children:
        huaweiPE:
          hosts:
            PE-KIROVSKIY:
              ansible_host: 198.51.100.3
              ansible_user: huawei
            PE-VOLGSKIY:
              ansible_host: 198.51.100.4
              ansible_user: huawei
    CPE: # clients
      children:
        mikrotik:
          hosts:
            CPE-5:
              ansible_host: 198.51.100.10
              ansible_user: ISP
            CPE-7:
              ansible_host: 198.51.100.14
              ansible_user: ISP
            CPE-4:
              ansible_host: 198.51.100.18
              ansible_user: ISP
            CPE-6:
              ansible_host: 198.51.100.22
              ansible_user: ISP
