---
- name: load IPAM_NETWORK to anounce IS-IS/BGP
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../IPAM_IP.yml"

- name: Get timestamp
  ansible.builtin.shell: "date +%Y%m%d_%H%M%S"
  delegate_to: localhost
  register: ts
  changed_when: false # false - never "changed" bc it isn't a configuration, it's pre_task on EVE-NG host

- name: Get general list # we're taking all string where hostname = inventory_hostname. See. IPAM_NETWORK.yml
  ansible.builtin.set_fact:
    list: "{{routers| selectattr('hostname', 'equalto', inventory_hostname) | list}}"

- name: Load auth password and method for IS-IS authentication
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../IS-IS/auth_password.yml"


- name: check that key-chain is exsist
  ecorouter.ecorouteros.ecorouteros_command:
    commands: 
      - "sh run | incl key chain "
  register: "check_key-chain"
- name: display warning to renew key-chain
  ansible.builtin.debug:
    msg: "There are all key chain on the router. Do you want to renew it?(All password will be zeroed)\n{{check_key-chain}}"
  when: check_key-chain | length > 0
- name: ask me to clear key chain

  ansible.builtin.pause:
    prompt: "Clear key-chain?"
  register: answer_key_chain

- name: deploy config
  block:
    - name: create key-chain
      ecorouter.ecorouteros.ecorouteros_config:
        lines:
          - "key-string {{ auth_to_huawei_password }}"
        parents:
          - "key chain IS-IS-{{ item.interface }}"
          - "key 1"
      loop: "{{ list }}"

    - name: enable auth on interfaces
      ecorouter.ecorouteros.ecorouteros_config:
        lines:
          - "isis auth mode {{ auth_to_ecorouter_method }}"
          - "isis auth key-chain IS-IS-{{ item.interface }}"
        parents:
          - "interface {{item.interface}}"
      loop: "{{ list }}"

    - name: print difference
      ecorouter.ecorouteros.ecorouteros_command:
        commands:
          - "sh ip int brief"
          - "sh isis interface"
      register: diff_output

    - name: print that was changed
      ansible.builtin.debug:
        msg: "{{diff_output.stdout_lines}}"

    - name: ask to me
      ansible.builtin.pause:
        prompt: "Commit? NO - reload(yes/no)"
      register: answer

    - name: commit if yes
      ecorouter.ecorouteros.ecorouteros_config:
        commands: write
      when: answer.user_input | lower == "yes"  #alwyas yes, not YeS, YES etc.

       # NEED TO FIND A NORMAL SOLUTION!
#    - name: reload prompt
#      ecorouter.ecorouteros.ecorouteros_command: # need to improve this moment, very bad solution
#        commands: "reload"
#        prompt:
#          - "reboot system (y/n):"
#        answer: "y"
#      when: answer.user_input | lower == "no"
  when: answer_key_chain.user_input | lower == "yes"

  rescue:
    - name: display warning
      ansible.builtin.debug:
        msg: "Someting broken or you want to backup. Need to reload router manualy!"

    - name: get difference
      ecorouter.ecorouteros.ecorouteros_command:
        commands:
          - "reload"
      register: diff_output

    - name: display difference
      ansible.builtin.debug:
        msg: "{{diff_output.stdout_lines[0]}}"

    - name: answer
      ansible.builtin.pause:
        prompt: "Reload?(yes/no)"
      register: reload_answer

    - name: rollback to backup
      ecorouter.ecorouteros.ecorouteros_command:
        commands:
          - "reload"
          - "y"
      when: reload_answer | lower == "yes"

    - name: message if no
      ansible.builtin.debug:
        msg: "Okay, reload canceled. Be carefull and check difference in your configs"
      when: reload_answer | lower == "no"

