---
- name: Gathering full display configuration
  hosts: CORE-SARATOV
  gather_facts: false #always!
  vars:
    timestamp: "{{lookup('pipe','date +%Y-%m-%d_%H:%M:%S')}}"

  tasks:
    - name: Gathering
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: output

    - name: save to file
      ansible.builtin.copy:
        content: "{{output.stdout | join('\n')}}" # ios_command return json with \n instead of whitespace 
        dest: "/root/github/Network-labs/Lab2/playbooks/sh-run/{{inventory_hostname}}_{{timestamp}}_config_.txt"
      delegate_to: localhost
