---
- name: Gathering full display configuration
  hosts: CORE-SARATOV
  gather_facts: false #always!
  vars:
    timestamp: "{{lookup('pipe','date +%Y-%m-%d_%H:%M:%S')}}"

  tasks:
    - name: Gathering
      ecorouter.ecorouteros.ecorouteros_facts: # give list!!!
        gather_subset:
          - config
      register: output

    - name: save to file
      ansible.builtin.copy:
        content: "{{output.ansible_facts.ansible_net_config}}" # ansible_facts.ansible_net_config transform to normal view; facts return json 
        dest: "/root/github/Network-labs/Lab2/playbooks/sh-run/{{inventory_hostname}}_{{timestamp}}_config_.txt"
      delegate_to: localhost
