---
- name: load IPAM_NETWORK to anounce IS-IS/BGP
  ansible.builtin.include_vars:
    file: "/workspaces/Network-labs/Lab2/IPAM_NETWORK.yml"
- name: Get timestamp
  ansible.builtin.shell: "date +%Y%m%d_%H%M%S"
  delegate_to: localhost
  register: ts
  changed_when: false # false - never "changed" bc it isn't a configuration, it's pre_task on EVE-NG host

- name: Get general list # we're taking all string where hostname = inventory_hostname. See. IPAM_NETWORK.yml
  ansible.builtin.set_fact:
    list: "{{routers| selectattr('hostname', 'equalto', inventory_hostname) | list}}"

- name: add IPv6
  ansible.builtin.set_fact:
    IPv6_list: "{{list | map(attribute='ipv6') | reject('equalto', 'not supported')| list}}"

- name: add IPv4 # difficult version + formating to IP mask - VERY KLUDGE SPECIALLY!
  ansible.builtin.set_fact:
    IPv4_list: >- # >- make string, not list
      {# create(or "int a" from C++) variable result how empety list #}
      {# {%- - delete whitespace %} #}
      {%- set result = [] -%}
      {# cycle with var item in list "list"#}
      {%- for item in list -%}
      {# condition if ipv4 in 1,2,3 etc stirng not equal not supported #}
      {%- if item.ipv4 != "not supported" -%}
      {# var ip - it's IPv4 string with cut /m #}
      {%- set ip = item.ipv4 | ansible.utils.ipaddr('network') -%}
      {# var map - it's IPv4 string with cut IP and transform /m into mask #}
      {%- set mask = item.ipv4 | ansible.utils.ipaddr('netmask') -%}
      {# set "trash" var _ from condition and record to var "result" to end of list #}
      {%- set _ = result.append(ip ~ ' ' ~ mask) -%}
      {%- endif -%}
      {%- endfor -%}
      {{ result | to_json }} 
# to_json convert [''] to [""] - that json are waiting
- name: convert string to list IPv4
  ansible.builtin.set_fact:
    IPv4_list: "{{IPv4_list | from_json}}" # from_json - converting string to list

- name: Set facts
  ansible.builtin.set_fact: 
    timestamp: "{{ ts.stdout | trim }}" # trim - remove whitespace

- name: debug_IPv4
  ansible.builtin.debug:
    msg:
      - "IPv4: {{item}}"
  loop: "{{IPv4_list}}"

- name: debug_IPv6
  ansible.builtin.debug:
    msg:
      - "IPv6: {{item}}"
  loop: "{{IPv6_list}}"
- name: interace list
  ansible.builtin.set_fact:
    interface: "{{list | map(attribute='interface') | list}}" # list interface with IP


- name: create_backup
  ansible.netcommon.cli_command:
    command: |
      save backup_{{timestamp}}.cfg
      y
- name: deploy config 
  block:
    - name: enable interface to IS-IS
      ansible.netcommon.ce_config:
      command: |
        isis enable 1
      parents: "interface {{item}}"
      loop: "{{interface}}"
      

    - name: print difference
      ansible.netcommon.cli_command:
        command: | 
          display isis interface
      register: diff_output

    - name: print that was changed
      ansible.builtin.debug:
        msg: "{{diff_output.stdout_lines}}"

    - name: ask to me
      ansible.builtin.pause:
        prompt: "Commit?(yes/no)"
      register: answer

    - name: commit if yes
      ansible.netcommon.cli_command:
        command: |
          system-view
          commit
          return
          save vrpcfg.cfg
          y
          y
      when: answer.user_input | lower == "yes" #alwyas yes, not YeS, YES etc.

    - name: clear conf if no
      ansible.netcommon.cli_command:
        command: |
          system-view
          clear configuration candidate
          load configuration file backup_{{timestamp}}.cfg replace
          commit
      when: answer.user_input | lower != "yes"
      ignore_errors: true #insurance if someone breaks

  rescue:
    - name: rollback to backup
      ansible.netcommon.cli_command:
        command: |
          system-view    
          load configuration file backup_{{timestamp}}.cfg replace
          commit
          quit
    - name: delete backup
      ansible.netcommon.cli_command:
        command: |
          delete /unreserved /quiet backup_{{timestamp}}.cfg
