---
- name: load IPAM_NETWORK to anounce IS-IS/BGP
  ansible.builtin.include_vars:
    file: "root/github/Network-labs/Lab2/IPAM_NETWORK.yml"
- name: Get timestamp
  ansible.builtin.shell: "date +%Y%m%d_%H%M%S"
  delegate_to: localhost
  register: ts
  changed_when: false # false - never "changed" bc it isn't a configuration, it's pre_task on EVE-NG host

- name: Get general list # we're taking all string where hostname = inventory_hostname(loop). See. IPAM_NETWORK.yml
  ansible.builtin.set_fact:
    # default([]) - create empety var; + [...] - add string; combine - update dictory; take field interface and change "e" to empety
    list: "{{ list  | default([]) + [item | combine({'interface': item.interface | regex_replace('^e', '')})] }}"
  loop: "{{ routers | selectattr('hostname', 'equalto', inventory_hostname) | list }}"

- name: Set facts
  ansible.builtin.set_fact: 
    timestamp: "{{ ts.stdout | trim }}" # trim - remove whitespace

- name: Get level
  ansible.builtin.shell: |
    awk -F'|' '/EDGE-SARATOV/{gsub(/ /,"",$5); print $5; exit}' /root/github/Network-labs/Lab2/routing-register.md
  delegate_to: localhost
  register: LEVEL
  changed_when: false

- name: Get NET
  ansible.builtin.shell: |
    awk -F'|' '/{{inventory_hostname}}/{gsub(/ /,"",$3); print $3; exit}' /root/github/Network-labs/Lab2/routing-register.md
  delegate_to: localhost
  register: NET
  changed_when: false

- name: set number of loopback
  ansible.builtin.shell: "echo {{list.item}} | rev | cut -c 1"
  register: number_loopback
  when: list.item == "loopback0"

- name: create_backup
  ansible.netcommon.cli_command:
    command: |
      save backup_{{timestamp}}.cfg
      y
- name: deploy config
  block:

    - name: enable IS-IS+NET
      community.network.ce_config:
        lines:
          - "net {{NET}}"
          - "is-level {{LEVEL}}"
        parents: 
          - "isis 1"

    - name: enable IPv6 on ethernet
      community.network.ce_config:
        lines:
          - "undo shutdown"
          - "ipv6 enable"
          - "ipv6 add {{list.ipv6}}"
        parents:
          - "interface Ethernet {{item.interface}}"
      loop: "{{list}}"
      when: list.ipv6 != "not supported"

    - name: enable interface IS-IS + p2p
      community.network.ce_config:
        lines:
          - "isis enable 1"
          - "isis circuit-level {{LEVEL}}"
          - "isis circuit-type p2p"
        parents:
          - "interface Ethernet {{item.interface}}"
      loop: "{{list}}"
      when: list.interface != "loopback0"

    - name: enable IPv4 on ethernet
      community.network.ce_config:
        lines:
          - "ip add {{ item.ipv4 | ansible.utils.ipaddr('address') }} {{ item.ipv4 | ansible.utils.ipaddr('netmask') }}"
        parents:
          - interface Ethernet {{item.interface}}
        loop: "{{list}}"
        when:
          - list.interface != "loopback0"

    - name: enable IP+NET on loopback
      community.network.ce_config:
        lines:
          - "ip add {{ item.ipv4 | ansible.utils.ipaddr('address') }} {{ item.ipv4 | ansible.utils.ipaddr('netmask') }}"
          - "isis enable 1"
          - "isis circuit-level {{LEVEL}}"
        parents:
          - interface loopback {{ numer_loopback }}
        loop: "{{list}}"
        when:
          - list.interface == "loopback0"
          - list.ipv6 == "not supported" # loopback now do not support IPv6, mb future it will be realized

    - name: get ISIS interface
      ansible.netcommon.cli_command:
        command: | 
          display isis interface
      register: isis_interface

    - name: print is-is
      ansible.builtin.debug:
        msg: "{{isis_interface.stdout[0]}}"

    - name: get interface
      ansible.netcommon.cli_command:
        command: | 
          display current interface
      register: settings_interface

    - name: print interface
      ansible.builtin.debug:
        msg: "{{settings_interface.stdout[0]}}"

    - name: ask to me
      ansible.builtin.pause:
        prompt: "Commit?(yes/no)"
      register: answer

    - name: commit if yes
      ansible.netcommon.cli_command:
        command: |
          system-view
          commit
          return
          save vrpcfg.cfg
          y
          y
      when: answer.user_input | lower == "yes" #alwyas yes, not YeS, YES etc.

    - name: clear conf if no
      ansible.netcommon.cli_command:
        command: |
          system-view
          clear configuration candidate
          load configuration file backup_{{timestamp}}.cfg replace
          commit
      when: answer.user_input | lower != "yes"
      ignore_errors: true #insurance if someone breaks

  rescue:
    - name: rollback to backup
      ansible.netcommon.cli_command:
        command: |
          system-view    
          load configuration file backup_{{timestamp}}.cfg replace
          commit
          quit
    - name: delete backup
      ansible.netcommon.cli_command:
        command: |
          delete /unreserved /quiet backup_{{timestamp}}.cfg
