---
- name: Load IP+Interface
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../IPAM_IP.yml"

- name: Load auth password and method for IS-IS authentication
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../IS-IS/auth_password.yml"

- name: Get timestamp
  ansible.builtin.shell: "date +%Y%m%d_%H%M%S"
  delegate_to: localhost
  register: ts
  changed_when: false # false - never "changed" bc it isn't a configuration, it's pre_task on EVE-NG host

- name: Get general list # we're taking all string where hostname = inventory_hostname(loop). See. IPAM_NETWORK.yml
  ansible.builtin.set_fact:
    # default([]) - create empety var; + [...] - add string; combine - update dictory; take field interface and change "e" to empety
    list: "{{ list  | default([]) + [item | combine({'interface': item.interface | regex_replace('^e', '')})] }}"
  loop: "{{ routers | selectattr('hostname', 'equalto', inventory_hostname) | list }}"

- name: Set facts
  ansible.builtin.set_fact:
    timestamp: "{{ ts.stdout | trim }}" # trim - remove whitespace


- name: Create_backup
  ansible.netcommon.cli_command:
    command: |
      save backup_{{timestamp}}.cfg
      y
- name: Deploy config
  block:

    - name: Set password to Ecorouter
      community.network.ce_config:
        lines:
          - isis auth {{ auth_to_ecorouter_method }} cipher {{ auth_to_ecorouter_password }}
        parents:
          - "interface Ethernet {{ item.interface }}"
      loop: "{{ list | selectattr('to', 'equalto', 'CORE-SARATOV') | list }}"

    - name: Set password to huawei
      community.network.ce_config:
        lines:
          - isis auth {{ auth_to_huawei_method }} key-id {{ auth_to_huawei_keyid }} cipher {{ auth_to_huawei_password }}
        parents:
          - "interface Ethernet {{ item.interface }}"
      loop: "{{ list | selectattr('to', 'ne', 'CORE-SARATOV') | list }}" # ne - not equalto

    - name: Get ISIS interface
      ansible.netcommon.cli_command:
        command: "display isis interface"
      register: isis_interface

    - name: Print is-is
      ansible.builtin.debug:
        msg: "{{ isis_interface.stdout_lines }}"

    - name: Ask to me
      ansible.builtin.pause:
        prompt: "Commit?(yes/no)"
      register: answer

    - name: Commit if yes
      ansible.netcommon.cli_command:
        command: |
          system-view
          commit
          return
          save vrpcfg.cfg
          y
          y
      when: answer.user_input | lower == "yes"  # alwyas yes, not YeS, YES etc.

    - name: Clear conf if no
      ansible.netcommon.cli_command:
        command: 
          system-view
          clear configuration candidate
          load configuration file backup_{{timestamp}}.cfg replace
          commit
      when: answer.user_input | lower != "yes"

  rescue:
    - name: Rollback to backup
      ansible.netcommon.cli_command:
        command: |
          system-view
          load configuration file backup_{{timestamp}}.cfg replace
          commit
          quit
    - name: Delete backup
      ansible.netcommon.cli_command:
        command: |
          delete /unreserved /quiet backup_{{timestamp}}.cfg
