---
- name: load metrics
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/../../IS-IS/METRICS.yml"

- name: Get timestamp
  ansible.builtin.shell: "date +%Y%m%d_%H%M%S"
  delegate_to: localhost
  register: ts
  changed_when: false # false - never "changed" bc it isn't a configuration, it's pre_task on EVE-NG host

- name: Get general list # we're taking all string where hostname = inventory_hostname(loop). See. IPAM_NETWORK.yml
  ansible.builtin.set_fact:
    list: "{{ routers | selectattr('hostname', 'equalto', inventory_hostname) | list }}"

- name: Set facts
  ansible.builtin.set_fact: 
    timestamp: "{{ ts.stdout | trim }}" # trim - remove whitespace

- name: create_backup
  ansible.netcommon.cli_command:
    command: |
      save backup_{{timestamp}}.cfg
      y
- name: deploy config
  block:

    - name: enable wide metric
      community.network.ce_config:
        lines:
          - cost-style wide
        parents:
          - "isis"

    - name: enable metrics on the interfaces
      community.network.ce_config:
        lines:
          - "isis cost {{item.cost}}"
        parents:
          - "interface Ethernet {{item.interface}}"
      loop: "{{list}}"

    - name: get ISIS interface
      ansible.netcommon.cli_command:
        command: "display isis interface"
      register: isis_interface

    - name: print is-is
      ansible.builtin.debug:
        msg: "{{isis_interface.stdout_lines}}"

    - name: get interface
      ansible.netcommon.cli_command:
        command: | 
          display current interface
      register: settings_interface

    - name: print interface
      ansible.builtin.debug:
        msg: "{{settings_interface.stdout_lines}}"

    - name: ask to me
      ansible.builtin.pause:
        prompt: "Commit?(yes/no)"
      register: answer

    - name: commit if yes
      ansible.netcommon.cli_command:
        command: |
          system-view
          commit
          return
          save vrpcfg.cfg
          y
          y
      when: answer.user_input | lower == "yes" #alwyas yes, not YeS, YES etc.

    - name: clear conf if no
      ansible.netcommon.cli_command:
        command: |
          system-view
          clear configuration candidate
          load configuration file backup_{{timestamp}}.cfg replace
          commit
      when: answer.user_input | lower != "yes"
      ignore_errors: true #insurance if someone breaks

  rescue:
    - name: rollback to backup
      ansible.netcommon.cli_command:
        command: |
          system-view    
          load configuration file backup_{{timestamp}}.cfg replace
          commit
          quit
    - name: delete backup
      ansible.netcommon.cli_command:
        command: |
          delete /unreserved /quiet backup_{{timestamp}}.cfg
